# Generated by Django 5.0.1 on 2024-07-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
    ]
