# Generated by Django 5.0.1 on 2024-09-18 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0005_sitebanner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitebanner',
            old_name='Image',
            new_name='image',
        ),
    ]
