# Generated by Django 5.0.1 on 2024-07-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_remove_user_mobile_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_author',
            field=models.TextField(blank=True, null=True),
        ),
    ]
